Add workflow dispatch and version override

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -10,10 +10,49 @@ on:
   release:
     types:
       - published
+  workflow_dispatch:
+    inputs:
+      version:
+        description: Application version to use when publishing the project
+        required: false
+      image-tag:
+        description: Additional Docker image tag to apply on deployment
+        required: false
 
 jobs:
+  # Determine version
+  version:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+
+    steps:
+      - name: Determine stable version
+        id: stable-version
+        if: ${{ github.event_name == 'release' || inputs.version }}
+        run: |
+          version="${{ inputs.version || github.event.release.tag_name }}"
+
+          if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z].*)?$ ]]; then
+              echo "Invalid version: $version"
+              exit 1
+          fi
+
+          echo "version=$version" >> $GITHUB_OUTPUT
+
+      - name: Determine prerelease version
+        id: pre-version
+        run: |
+          hash="${{ github.event.pull_request.head.sha || github.sha }}"
+          echo "version=0.0.0-ci-${hash:0:7}" >> $GITHUB_OUTPUT
+
+    outputs:
+      version: ${{ steps.stable-version.outputs.version || steps.pre-version.outputs.version }}
+
   # Build the image without deploying just to make sure the dockerfile is valid
   pack:
+    needs: version
+
     strategy:
       matrix:
         app:
@@ -44,11 +83,13 @@ jobs:
           docker buildx build .
           --file ${{ matrix.dockerfile }}
           --platform linux/amd64,linux/arm64
+          --build-arg VERSION=${{ needs.version.outputs.version }}
           --output type=tar,dest=image.tar
 
   # Build and deploy the image
   deploy:
     if: ${{ github.event_name != 'pull_request' }}
+    needs: version
 
     strategy:
       matrix:
@@ -89,7 +130,9 @@ jobs:
           docker buildx build .
           --file ${{ matrix.dockerfile }}
           --platform linux/amd64,linux/arm64
+          --build-arg VERSION=${{ needs.version.outputs.version }}
           --push
           --tag ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:latest
           ${{ github.event_name == 'release' && format('--tag ghcr.io/{0}/{1}:{2}', github.repository_owner, matrix.name, github.ref_name) || '' }}
           ${{ github.event_name == 'release' && format('--tag ghcr.io/{0}/{1}:stable', github.repository_owner, matrix.name) || '' }}
+          ${{ inputs.image-tag && format('--tag ghcr.io/{0}/{1}:{2}', github.repository_owner, matrix.name, inputs.image-tag) || '' }}
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,6 +10,11 @@ on:
   release:
     types:
       - published
+  workflow_dispatch:
+    inputs:
+      version:
+        description: Application version to use when publishing the project
+        required: false
 
 env:
   # Setting these variables allows .NET CLI to use rich color codes in console output
@@ -47,18 +52,19 @@ jobs:
     steps:
       - name: Determine stable version
         id: stable-version
-        if: ${{ github.event_name == 'release' }}
+        if: ${{ github.event_name == 'release' || inputs.version }}
         run: |
-          if ! [[ "${{ github.event.release.tag_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z].*)?$ ]]; then
-              echo "Invalid version: ${{ github.event.release.tag_name }}"
+          version="${{ inputs.version || github.event.release.tag_name }}"
+          
+          if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z].*)?$ ]]; then
+              echo "Invalid version: $version"
               exit 1
           fi
           
-          echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
+          echo "version=$version" >> $GITHUB_OUTPUT
 
       - name: Determine prerelease version
         id: pre-version
-        if: ${{ github.event_name != 'release' }}
         run: |
           hash="${{ github.event.pull_request.head.sha || github.sha }}"
           echo "version=0.0.0-ci-${hash:0:7}" >> $GITHUB_OUTPUT
@@ -80,7 +86,7 @@ jobs:
         uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # 3.2.0
         with:
           dotnet-version: 8.0.x
-          
+
       - name: Validate format
         run: dotnet format --verify-no-changes
 
